# GENERATED BY GEMINI

# Use the official lightweight Python image
FROM python:3.11-slim

# Set the working directory inside the container
WORKDIR /code

# Copy the requirements file first (for caching)
COPY ./requirements.txt /code/requirements.txt

# Install dependencies
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

# Copy the rest of your application code
COPY ./api /code/api

# Run the application
# Note: api.main:app points to api/main.py -> app object
# Note: --port 7860 is REQUIRED by Hugging Face Spaces
CMD ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "7860"]